### ISSUE TITLE
Can't export with new version 41

### ISSUE THREAD

**Issue by poorfish** [GeertWille/sketch-export-assets#58]

**Comment by stefanspieler** [comment]
Same here. A fix would be appreciated

**Comment by andreffernandes** [comment]
I really need a fix at this plugin

**Comment by Mettegry** [comment]
Same problem here. Hoping for a quick fix.

**Comment by perteraul** [comment]
Same here.

**Comment by vloboda** [comment]
Same here :(

**Comment by vic-tort** [comment]
Same here with 41. After choosing where to export nothing happens. Downgraded to Sketch 40.3 only because of this plugin :)

**Comment by josephjpearce** [comment]
Same here.

**Comment by oscarbicadaiii** [comment]
I love the new Sketch 41 version but without this plugin, I won't be upgrading. Hoping for a fix in the future. Thanks for your good work Sir!

**Comment by GeertWille** [comment]
For now sign up [here](http://sketchexporter.co/). We will be rolling out to beta users in the next few weeks.

**Comment by willizwx2015** [comment]
Same here:(:(:(

**Comment by ronaldo-getreveel** [comment]
Its not working.  Lets switch to another plugin.

**Comment by charlesmudy** [comment]
So I managed to create a fix, you can the updated version [here](https://github.com/charlesmudy/sketch-export-assets). @GeertWille I didn't want to create a pull request, I'm not really a programmer ... I simply found the solution [here](https://github.com/zmalltalker/sketch-android-assets/blob/cd0bbcb52713b7f3ee033f073f5cde2719683ce8/Generate%20Android%20Assets.jstalk) and since yours supports multiple devices, its more useful.

NOTE: The background issue seems to be back, so you need to do it the old way of copying your element to a new artboard without background @GeertWille maybe you can look into this?

@willizwx2015 @josephjpearce @vloboda @vic-tort @perteraul @Mettegry @stefanspieler

**Comment by GeertWille** [comment]
Thanks for fixing it. Though I'm not going to merge it since it removes a lot of other logic that shouldn't be removed. I would suggest keep using 40.3 for a few more days/weeks and after that you probably have a beta invite for [my all new plugin](http://sketchexporter.co/). It's free, works for all major Sketch version and is a lot speedier than this one. Not to mention it will have much better support, will be frequently updated with new features and we'll make sure it'll keep working with future Sketch updates as well. So again: for everyone's sake, do [sign up](http://sketchexporter.co/) :wink: 

@willizwx2015 @josephjpearce @vloboda @vic-tort @perteraul @Mettegry @stefanspieler @charlesmudy

**Comment by michailkouroupakis** [comment]
@charlesmudy i think there is still a problem with export with change settings. If i change @1x @2x @3x always the export sizes are same :(

**Comment by willizwx2015** [comment]
@charlesmudy can't change @1x @2x @3x always the export sizes are same :(

**Comment by michailkouroupakis** [comment]
First of all i think that the correct implementation of a export plugin will be like that [](http://image.prntscr.com/image/98ec186c650644378366bb8f1e1e761a.png)   The new plugin it is not very usable :( @GeertWille and restrict options

**Comment by GeertWille** [comment]
@michailkouroupakis we will be implementing a UI in the future. I know it restricts some options compared to this version but it will change over time.

**Comment by annawchou** [comment]
i'm also having the same issues too. i try to export and no files show up anywhere after i upgraded to the latest sketch (41.4) now it has stopped working. :/

**Comment by michailkouroupakis** [comment]
First of all we must be thankful for GeertWille i think the new plugin will be da best. 
For now @annawchou @willizwx2015 @charlesmudy @josephjpearce @vic-tort @andreffernandes @stefanspieler @Mettegry i have found similiar plugins for export 1x 2x Android iOS. i know it is not the best possible solution but for now i thinks its ok!
https://github.com/nickstamas/Sketch-Better-Android-Export
https://github.com/leonspok/Scaled-Export-for-iOS

**Comment by GeertWille** [comment]
Right now we are running a beta for a reason... We want to gather feedback of you guys and change the product to fit your and our needs. So please if you think this plugin is useful try to look at the new one with an open mind and give us as much as feedback as you can (not here but on the fb page). And yes we will be adding a UI in the near future. Just give us some time :)

**Comment by mrfriki** [comment]
Any ETA for the new plugin or beta version? Just signed to the newsletter and I'm eager for more news :)

I don't care to wait since this is the best export plugin by far, Also I don't mind if it is become a paid plugin since it saves us dozens of hours of tedious work. However it would be cool to have an estimate of the time in order to evaluate our options in this idle time (we also have work to do :)

**Comment by GeertWille** [comment]
If you provide me with the name you signed up I can give you early access :)

**Comment by mrfriki** [comment]
Hey, thanks for just fast answer! I signed as Rubén Santiago (Bitban). Thanks so much.

**Comment by charlesmudy** [comment]
@GeertWille can I test it as well "Shina" ... signed up about a week ago

**Comment by GeertWille** [comment]
@mrfriki @charlesmudy Okay, you'll be getting an email in about 30 minutes. Please if you have any questions or feedback there will be a link to a private facebook group in the email and also in the menu of the plugin. Do request access to the group so I can give you help there. I also try to fix this plugin so you can install them both and compare.

**Comment by charlesmudy** [comment]
@GeertWille Thanks! Also if you can fix this one, it would be great as I don't want to keep patching my version. Some of us are using it on current project(s) and the updates just keeps adding un-necessary stuffs like /res/ folder, opening folders e.t.c. Its confusing my devs. All these features should be optional.

Looking forward to the new version

**Comment by GeertWille** [comment]
@charlesmudy that's why we are creating a closed version based on the workflow in our company and on all your feedback ;)

**Comment by GeertWille** [comment]
this plugin should be fixed now btw...

**Comment by annawchou** [comment]
@GeertWille thanks for sending me the beta! I just downloaded it and it still doesn't work. Keeps giving me an error saying it couldn't find any slices.. also not sure why it needs to be a slice in order to be exported and why not just from an artboard such as before? thanks!
